# Generated by Django 5.0.6 on 2024-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chatlink_chattable_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlink",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
